AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
